// Auto-generated by fnrpc. DO NOT EDIT.
// This file has been generated by Specta. Do not edit this file manually.
export type AsrRunInfo = {
	engine: string,
	device: string,
	compute_type: string | null,
	gpu_attempted: boolean | null,
	fallback_to_cpu: boolean | null,
};

export type Capabilities = {
	webgpu: boolean,
	vulkan: boolean,
	cuda: boolean,
	rocm: boolean,
	directml: boolean,
	mps: boolean,
	openvino: boolean,
};

export type CpuInfo = {
	model: string,
	cores: number,
	speed_mhz: number | null,
};

export type DeviceInfo = {
	platform: PlatformInfo,
	cpu: CpuInfo,
	memory: MemoryInfo,
	gpu: GpuInfo[],
	ort: OrtInfo,
};

export type DirEntry = {
	name: string,
	is_dir: boolean,
	size: bigint | null,
};

export type FoundVia = "Mdns" | "Default" | "PortFile";

export type FrameRate = {
	numerator: number,
	denominator: number,
};

export type GpuInfo = {
	name: string,
	vendor: Vendor,
	architecture: string | null,
	driver_version: string,
	temperature: number | null,
	gpu_percent: number | null,
	gfx_version: string | null,
	vram: VramInfo,
	capabilities: Capabilities,
	hsa_override_gfx: string | null,
	vulkan_heaps: VulkanHeaps | null,
	op_probes: OpProbes | null,
};

export type GroupInfo = {
	group_id: string,
	task_count: number,
	created_at: string | null,
	tasks: TaskBrief[],
};

export type MemoryInfo = {
	total: string,
	free: string,
	process_heap_used: string,
};

export type OpProbes = {
	torch_conv1d: ProbeResult | null,
};

export type OrtBackend = {
	name: string,
	bundled: boolean,
};

export type OrtInfo = {
	version: string,
	backends: OrtBackend[],
};

export type PlatformInfo = {
	os: string,
	arch: string,
	release: string,
	hostname: string,
	runtime: string,
	runtime_version: string,
	node_version: string | null,
};

export type ProbeResult = "Ok" | "Fail";

/**
 *  An RPC error returned by any handler (query, mutate, subscribe).
 * 
 *  Maps to [`RpcError`](https://docs.rs/fnrpc-client/latest/fnrpc_client/class.RpcError.html)
 *  in the TypeScript client.
 * 
 *  # TS mirror
 * 
 *  ```typescript
 *  class RpcError extends Error {
 *    name: "RpcErr";
 *    code: string;
 *    message: string;
 *    data: unknown;
 *  }
 *  ```
 */
export type RpcErr = {
	name: string,
	code: string,
	message: string,
	data: unknown | null,
};

export type RunInfo = {
	asr: AsrRunInfo | null,
};

export type ServerInfo = {
	host: string,
	port: number,
	found_via: FoundVia,
};

/**  Server type identifiers for mDNS discovery. */
export type ServerType = "VoxcpmTorchGradio" | "DemucsTorchServer";

export type Task = {
	id: string,
	source: VideoSource,
	url: string,
	title: string | null,
	status: string,
	current_stage: string | null,
	task_dir: string,
	final_video_path: string | null,
	error_message: string | null,
	created_at: string,
	started_at: string | null,
	completed_at: string | null,
};

export type TaskBrief = {
	id: string,
	title: string | null,
	status: string,
	current_stage: string | null,
	created_at: string,
	started_at: string | null,
	completed_at: string | null,
	error_message: string | null,
};

export type TaskCtx = {
	task: Task,
	stages: TaskStage[] | null,
	pipeline: string,
	last_run_pipeline: string | null,
	input: unknown,
	frame_rate: FrameRate,
	run_info: RunInfo | null,
	video_source_path: string | null,
	audio_source_path: string | null,
	asr_language: string | null,
	target_language: string | null,
};

export type TaskStage = {
	name: string,
	label: string,
	status: string,
	progress: number | null,
	started_at: string | null,
	completed_at: string | null,
	last_message: string | null,
	error_message: string | null,
};

export type Vendor = "Amd" | "Nvidia" | "Intel" | "Unknown";

export type VideoSource = "Youtube" | "Bilibili" | "Local" | "Remote" | "Unknown";

export type VramInfo = {
	percent: number | null,
	total: number | null,
	used: number | null,
	type: VramType | null,
	reserved: number | null,
	gtt: number | null,
};

export type VramType = "Dedicated" | "Shared" | "Unknown";

export type VulkanHeaps = {
	device_local: number | null,
	host_visible: number | null,
};

export type Procedures = {
  read_app_file_text: { kind: "query"; method: "GET"; input: string; output: string; error: RpcErr };
  write_app_file_text: { kind: "mutate"; method: "POST"; input: [string, string]; output: null; error: RpcErr };
  read_app_file_bin: { kind: "query"; method: "GET"; input: string; output: number[]; error: RpcErr };
  list_app_directory: { kind: "query"; method: "GET"; input: string; output: DirEntry[]; error: RpcErr };
  watch_task_log: { kind: "subscribe"; method: "GET"; input: string; output: string; error: RpcErr };
  tick: { kind: "subscribe"; method: "GET"; input: bigint; output: bigint; error: RpcErr };
  get_group_list: { kind: "query"; method: "GET"; input: null; output: GroupInfo[]; error: RpcErr };
  get_task_ctx: { kind: "query"; method: "GET"; input: string; output: TaskCtx; error: RpcErr };
  health_check: { kind: "query"; method: "GET"; input: null; output: string; error: RpcErr };
  get_count: { kind: "query"; method: "GET"; input: null; output: string; error: RpcErr };
  reset_count: { kind: "mutate"; method: "POST"; input: null; output: null; error: RpcErr };
  find_server: { kind: "query"; method: "GET"; input: ServerType; output: ServerInfo; error: RpcErr };
  start_torch: { kind: "mutate"; method: "POST"; input: null; output: number; error: RpcErr };
  stop_torch: { kind: "mutate"; method: "POST"; input: null; output: null; error: RpcErr };
  check_torch: { kind: "query"; method: "GET"; input: null; output: boolean; error: RpcErr };
  start_voxcpm: { kind: "mutate"; method: "POST"; input: null; output: number; error: RpcErr };
  stop_voxcpm: { kind: "mutate"; method: "POST"; input: null; output: null; error: RpcErr };
  device_info: { kind: "query"; method: "GET"; input: null; output: DeviceInfo; error: RpcErr };
  resume_task: { kind: "mutate"; method: "POST"; input: [string, string]; output: null; error: RpcErr };

}

export const __procedureMeta = {
  read_app_file_text: { kind: "query", method: "GET" },
  write_app_file_text: { kind: "mutate", method: "POST" },
  read_app_file_bin: { kind: "query", method: "GET" },
  list_app_directory: { kind: "query", method: "GET" },
  watch_task_log: { kind: "subscribe", method: "GET" },
  tick: { kind: "subscribe", method: "GET" },
  get_group_list: { kind: "query", method: "GET" },
  get_task_ctx: { kind: "query", method: "GET" },
  health_check: { kind: "query", method: "GET" },
  get_count: { kind: "query", method: "GET" },
  reset_count: { kind: "mutate", method: "POST" },
  find_server: { kind: "query", method: "GET" },
  start_torch: { kind: "mutate", method: "POST" },
  stop_torch: { kind: "mutate", method: "POST" },
  check_torch: { kind: "query", method: "GET" },
  start_voxcpm: { kind: "mutate", method: "POST" },
  stop_voxcpm: { kind: "mutate", method: "POST" },
  device_info: { kind: "query", method: "GET" },
	resume_task: { kind: "mutate", method: "POST" },
} as const;
